import type { Metadata } from "next";
import { GeistSans, GeistMono } from "geist/font";
import "./globals.css";

const siteUrl = "https://appstoreposition.com";
const siteName = "App Store Position";
const siteDescription = "Track your favorite crypto app rankings on the App Store. Get free daily email notifications with position updates for Coinbase, Polymarket, Phantom, and more.";

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: "App Store Position - Daily Crypto App Ranking Notifications",
    template: "%s | App Store Position",
  },
  description: siteDescription,
  keywords: [
    "app store rankings",
    "crypto app tracker",
    "app store position",
    "coinbase ranking",
    "polymarket app store",
    "phantom wallet ranking",
    "app store notifications",
    "finance app charts",
    "iOS app rankings",
  ],
  authors: [{ name: "Oleg Giberstein", url: "https://coinrule.com" }],
  creator: "Oleg Giberstein",
  publisher: siteName,
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    url: siteUrl,
    siteName: siteName,
    title: "App Store Position - Daily Crypto App Ranking Notifications",
    description: siteDescription,
    // Images are auto-generated by opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: "App Store Position - Daily Crypto App Ranking Notifications",
    description: siteDescription,
    creator: "@ogiberstein",
    // Images are auto-generated by twitter-image.tsx
  },
  alternates: {
    canonical: siteUrl,
  },
  category: "technology",
};

// JSON-LD Schema for rich snippets
const jsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "WebSite",
      "@id": `${siteUrl}/#website`,
      url: siteUrl,
      name: siteName,
      description: siteDescription,
      publisher: { "@id": `${siteUrl}/#organization` },
    },
    {
      "@type": "Organization",
      "@id": `${siteUrl}/#organization`,
      name: siteName,
      url: siteUrl,
      logo: {
        "@type": "ImageObject",
        url: `${siteUrl}/icon.png`,
      },
      sameAs: [
        "https://coinrule.com",
        "https://limits.trade",
      ],
    },
    {
      "@type": "WebApplication",
      "@id": `${siteUrl}/#app`,
      name: siteName,
      description: siteDescription,
      url: siteUrl,
      applicationCategory: "FinanceApplication",
      operatingSystem: "Web",
      offers: {
        "@type": "Offer",
        price: "0",
        priceCurrency: "USD",
      },
      featureList: [
        "Daily App Store ranking notifications",
        "Track multiple crypto apps",
        "Free email alerts",
        "Coinbase, Polymarket, Phantom tracking",
      ],
    },
    {
      "@type": "FAQPage",
      "@id": `${siteUrl}/#faq`,
      mainEntity: [
        {
          "@type": "Question",
          name: "What apps can I track?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "You can track Coinbase, Crypto.com, Kraken, Polymarket, and Phantom Wallet rankings in the US Finance App Store charts.",
          },
        },
        {
          "@type": "Question",
          name: "How often are rankings updated?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Rankings are fetched and emailed to you daily. The data comes from the top 200 free Finance apps in the US App Store.",
          },
        },
        {
          "@type": "Question",
          name: "Is App Store Position free?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Yes, App Store Position is completely free to use. Simply enter your email and select the apps you want to track.",
          },
        },
      ],
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body
        className={`${GeistSans.variable} ${GeistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
} 